dataset_root_path: data/raw/
dataset_combined_path: data/processed/combined.pkl
dataset_cleaned_path: data/processed/cleaned.pkl

x_train_path: data/processed/x_train.pkl
y_train_path: data/processed/y_train.pkl
x_valid_path: data/processed/x_valid.pkl
y_valid_path: data/processed/y_valid.pkl
x_test_path: data/processed/x_test.pkl
y_test_path: data/processed/y_test.pkl

x_train_prep_path: data/processed/x_train_prep.pkl
y_train_prep_path: data/processed/y_train_prep.pkl
x_valid_prep_path: data/processed/x_valid_prep.pkl
y_valid_prep_path: data/processed/y_valid_prep.pkl
x_test_prep_path: data/processed/x_test_prep.pkl
y_test_prep_path: data/processed/y_test_prep.pkl

ohe_station_path: models/ohe_stasiun.pkl

minmax_path: models/minmax.pkl
rmout_minmax_path: models/rmout_minmax.pkl

std_path: models/std.pkl
rmout_std_path: models/rmout_std.pkl
minmax_std_path: models/minmax_std.pkl
rmout_minmax_std_path: models/rmout_minmax_std.pkl

datetime_columns:
- tanggal
int32_columns:
- pm10
- pm25
- so2
- co
- o3
- no2
- max
object_columns:
- stasiun
- critical
- categori

predictors:
- stasiun
- pm10
- pm25
- so2
- co
- o3
- no2
predictors_feature_engineered:
- pm10
- pm25
- so2
- co
- o3
- no2
target: categori
target_categories:
- BAIK
- SEDANG
- TIDAK SEHAT
target_categories_new:
- BAIK
- TIDAK BAIK

missing_value_co: 11
missing_value_no2: 18
missing_value_o3: 29
missing_value_pm10:
  BAIK: 28
  TIDAK BAIK: 55
missing_value_pm25:
  BAIK: 38
  TIDAK BAIK: 82
missing_value_so2: 35

range_co:
- -1
- 100
range_no2:
- -1
- 100
range_o3:
- -1
- 160
range_pm10:
- -1
- 800
range_pm25:
- -1
- 400
range_so2:
- -1
- 500
range_stasiun:
- DKI1 (Bunderan HI)
- DKI2 (Kelapa Gading)
- DKI3 (Jagakarsa)
- DKI4 (Lubang Buaya)
- DKI5 (Kebon Jeruk) Jakarta Barat
